### ISSUE TITLE
Toolkit for patching ffmpeg, running NW.js and packaging applications.

### ISSUE THREAD

**Issue by davidmartinez10** [nwutils/nwutils.github.io#12]
Hi! I just published this package that includes some tools to help ease some annoyances:
[nwts-tools](https://github.com/davidmartinez10/nwts-tools)

And this project starter that takes full advantage of its features, including integration with the VSCode debugger out-of-the-box:
[nwts-solid-starter](https://github.com/davidmartinez10/nwts-solid-starter)

I hope you like them or find them useful.

**Comment by TheJaredWilcurt** [comment]
Added
