### ISSUE TITLE
Request addition to  Boilerplates

### ISSUE THREAD

**Issue by codeh2o** [nwutils/nwutils.github.io#15]
Dear nwutils:
I recently create a boilerplate named "NW-Vue3-Typescript-Pinia".I wish it could be add into nw Boilerplate for helping more developers.
NW-Vue3-Typescript-Pinia is an open-source project based on NW.js, Vue 3, Typescript, and Pinia, designed to help developers quickly build applications on the NW.js platform.

the project url is  [https://github.com/codeh2o/nw-vue3-typescript-pinia](https://github.com/codeh2o/nw-vue3-typescript-pinia)

**Comment by TheJaredWilcurt** [comment]
I've added it to the README in that repo under the list of alternatives. I don't see this as fundamentally different enough to justify taking up a big block of space on the main website. Maybe I need to consider a redesign of how to convey information about the boilerplates.

* https://github.com/nwutils/nw-vue3-boilerplate#alternatives
