### ISSUE TITLE
no-build configuration tools

### ISSUE THREAD

**Issue by naviapis** [nwutils/nwutils.github.io#16]
Create NW.js React apps with no build configuration.
https://github.com/naviapps/create-nw-react-app

Added multi-platform builds like v3 to nw-builder.
https://github.com/naviapps/nw-builder-platforms

**Comment by TheJaredWilcurt** [comment]
Added these to the **Alternatives** sections of the existing recommended repos, to match how the Vue boilerplates handle spreading awareness of alternatives:

* https://github.com/nwutils/nw-react-example#alternatives
* https://github.com/nwutils/nw-builder#alternatives
* https://github.com/nwutils/nw-vue3-boilerplate#alternatives
* https://github.com/nwutils/nw-vue-cli-example#alternatives
