### ISSUE TITLE
[ADD] NW.js + SvelteKit Boilerplate

### ISSUE THREAD

**Issue by edde746** [nwutils/nwutils.github.io#20]
* **Project Name:** NW.js + SvelteKit Boilerplate
* **Project URL:** https://github.com/edde746/nwjs-sveltekit-boilerplate
* **Project Description:** Simple, unopinionated NW.js + SvelteKit Boilerplate with automated builds
**Type:** Boilerplates

**List any alternative or similar projects:**

* [peter23/NW.js-svelte-boilerplate](https://github.com/peter23/NW.js-svelte-boilerplate)

**Why is this the best one?**

The only other "alternative" was last updated 5 years ago.

**Comment by TheJaredWilcurt** [comment]
Waiting on https://github.com/edde746/nwjs-sveltekit-boilerplate/issues/1 to be resolved.

**Comment by TheJaredWilcurt** [comment]
Your default getting started instructions also should not include `bun`, as it does not run Windows either.

**Comment by edde746** [comment]
You're right, that was a typo. It should all be working fine on Windows now.
